Blog/Controllers/PanelController.cs
using Blog.Data.FileManager;
using Blog.Models;
using Blog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Blog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PanelController : Controller
    {
        private IRepository _repo;
        private IFileManager _fileManager;

        public PanelController(
            IRepository repo,
            IFileManager fileManager
            )
        {
            _repo = repo;
            _fileManager = fileManager;
        }

        public IActionResult Index()
        {
            var posts = _repo.GetAllPosts();
            return View(posts);
        }
        
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View(new PostViewModel());
            }
            else
            {
                var post = _repo.GetPost((int)id);
                return View(new PostViewModel {
                    Id = post.Id,
                    Title = post.Title,
                    Body = post.Body,
                    CurrentImage = post.Image,
                    Description = post.Description,
                    Tags= post.Tags,
                    Category= post.Category
                });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PostViewModel vm)
        {
            var post = new Post
            {
                Id = vm.Id,
                Title = vm.Title,
                Body = vm.Body,
                Description = vm.Description,
                Tags = vm.Tags,
                Category = vm.Category
            };

            if (vm.Image == null)
            {
                post.Image = vm.CurrentImage;
            } else
            {
                if (!string.IsNullOrEmpty(vm.CurrentImage))
                {
                    _fileManager.RemoveImage(vm.CurrentImage);
                }
                post.Image = await _fileManager.SaveImage(vm.Image);
            }

            if (post.Id > 0)
            {
                _repo.UpdatePost(post);
            }
            else
            {
                _repo.AddPost(post);
            }

            if (await _repo.SaveChangesAsync())
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(post);
            }

        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            _repo.RemovePost(id);
            await _repo.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Blog/Views/Panel/Edit.cshtml
@model PostViewModel

@{

}
<link href="~/lib/Trumbowyg-master/dist/ui/trumbowyg.min.css" rel="stylesheet" />
<div>
    <form asp-controller="Panel" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <div>
            <label>Title</label>
            <input asp-for="Title" />
        </div>
        <div>
            <label>Description</label>
            <input asp-for="Description" />
        </div>
        <div>
            <label>Tags</label>
            <input asp-for="Tags" />
        </div>
        <div>
            <label>Category</label>
            <select asp-for="Category">
                <option value="Travel">Travel</option>
                <option value="Programming">Programming</option>
                <option value="Photography">Photography</option>
            </select>
        </div>
        <div>
            <label>Body</label>
            <textarea id="editor" asp-for="Body"></textarea>
        </div>
        <div>
            <label>Image</label>
            <input asp-for="CurrentImage" type="hidden" />
            <input asp-for="Image" />
        </div>
        <div>
            <input type="submit" name="submit" value="Submit" />
        </div>
    </form>
</div>

@section  scripts {
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="~/lib/Trumbowyg-master/dist/trumbowyg.min.js"></script>
    <script>
        $('#editor').trumbowyg();

    </script>
    }

Blog/Views/Panel/Index.cshtml
@model IEnumerable<Post>

@{

}
<h2>Admin Panel</h2>

<div>
    <ul>
        @foreach (var post in Model)
        {
        <li>
            @post.Title
            -
            <a asp-controller="Panel" asp-action="Edit" asp-route-id="@post.Id">
                Edit
            </a>
            -
            <a asp-controller="Panel" asp-action="Remove" asp-route-id="@post.Id">
                Remove
            </a>
        </li>
        }
    </ul>
</div>